import { combineReducers } from 'redux'
import Myitem from './Myitem'
import PrintDialog from './PrintDialog'
import tradeOrderTable from './tradeOrderTable'
import weighOrderTable from './weighOrderTable'
import SendErrorOrderTable from './SendErrorOrderTable'
import WaitPrintOrderTable from './WaitPrintOrderTable'
import GoodsListTable from './GoodsListTable'
import SweepCodeCheckSendTable from './SweepCodeCheckSendTable'
import ErrorOrder from './ErrorOrder'
import batchWeighOper from './batchWeighOper'
import TradeSync from './TradeSync'
import LogisticModal from './LogisticModal'
import CheckOrders from './CheckOrders'
import WaitWeigh from './WaitWeigh'
import Refund from './Refund'
import MatchTable from './MatchTable'
import MatchCheck from './MatchCheck'
import LogisticsMatch from './LogisticsMatch'
import GoodsMatch from './GoodsMatch'
import ScanCodeWeigh from './ScanCodeWeigh'
import StockControl from './StockControl'
import StockEnter from './StockEnter'
import StockEnterData from './StockEnterData'
import StockCheckTable from './StockCheckTable'
import StockCheck from './StockCheck'
import ElecFaceModal from './ElecFaceModal'
import PrintSet from './PrintSet'
import AutoEva from './AutoEva'
import Message from './Message'
import WangBlacklist from './WangBlacklist'
import DistrictIntercept from './DistrictIntercept'
import ReceiverIntercept from './ReceiverIntercept'
import WangwangFilter from './WangwangFilter'
import BabyFilter from './BabyFilter'
import InterceptRecord from './InterceptRecord'
import InGeneralSituation from './InGeneralSituation'
import TradeListOne from './TradeListOne'
import InBasicSettings from './InBasicSettings'

import ServiceRate from './ServiceRate'
export  {ServiceRate,InBasicSettings,InGeneralSituation,InterceptRecord,BabyFilter,WangwangFilter,ReceiverIntercept,DistrictIntercept,WangBlacklist,TradeListOne,Message,AutoEva, GoodsMatch, SendErrorOrderTable,Myitem, tradeOrderTable, ErrorOrder, TradeSync, CheckOrders, weighOrderTable, WaitPrintOrderTable, PrintDialog, batchWeighOper, SweepCodeCheckSendTable, WaitWeigh, Refund, MatchTable, MatchCheck, ScanCodeWeigh,GoodsListTable,StockControl, StockEnter,StockEnterData,  LogisticsMatch, LogisticModal, StockCheckTable, StockCheck, ElecFaceModal, PrintSet}

